package greenInvoice.maps;
// Generated 19 Feb, 2019 9:57:44 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Accounts generated by hbm2java
 */
public class Accounts  implements java.io.Serializable {


     private int accountid;
     private Integer customerid;
     private Date accountopendate;
     private String accountname;
     private String otheraccountdetail;
     private Double payable;

    public Accounts() {
    }

	
    public Accounts(int accountid) {
        this.accountid = accountid;
    }
    public Accounts(int accountid, Integer customerid, Date accountopendate, String accountname, String otheraccountdetail, Double payable) {
       this.accountid = accountid;
       this.customerid = customerid;
       this.accountopendate = accountopendate;
       this.accountname = accountname;
       this.otheraccountdetail = otheraccountdetail;
       this.payable = payable;
    }
   
    public int getAccountid() {
        return this.accountid;
    }
    
    public void setAccountid(int accountid) {
        this.accountid = accountid;
    }
    public Integer getCustomerid() {
        return this.customerid;
    }
    
    public void setCustomerid(Integer customerid) {
        this.customerid = customerid;
    }
    public Date getAccountopendate() {
        return this.accountopendate;
    }
    
    public void setAccountopendate(Date accountopendate) {
        this.accountopendate = accountopendate;
    }
    public String getAccountname() {
        return this.accountname;
    }
    
    public void setAccountname(String accountname) {
        this.accountname = accountname;
    }
    public String getOtheraccountdetail() {
        return this.otheraccountdetail;
    }
    
    public void setOtheraccountdetail(String otheraccountdetail) {
        this.otheraccountdetail = otheraccountdetail;
    }
    public Double getPayable() {
        return this.payable;
    }
    
    public void setPayable(Double payable) {
        this.payable = payable;
    }




}


