package greenInvoice.maps;
// Generated 19 Feb, 2019 9:57:44 PM by Hibernate Tools 4.3.1



/**
 * Chemicals generated by hbm2java
 */
public class Chemicals  implements java.io.Serializable {


     private Integer productcode;
     private String productdesc;
     private String specification;
     private String packsize;
     private Double price;
     private Float gst;

    public Chemicals() {
    }

    public Chemicals(String productdesc, String specification, String packsize, Double price, Float gst) {
       this.productdesc = productdesc;
       this.specification = specification;
       this.packsize = packsize;
       this.price = price;
       this.gst = gst;
    }
   
    public Integer getProductcode() {
        return this.productcode;
    }
    
    public void setProductcode(Integer productcode) {
        this.productcode = productcode;
    }
    public String getProductdesc() {
        return this.productdesc;
    }
    
    public void setProductdesc(String productdesc) {
        this.productdesc = productdesc;
    }
    public String getSpecification() {
        return this.specification;
    }
    
    public void setSpecification(String specification) {
        this.specification = specification;
    }
    public String getPacksize() {
        return this.packsize;
    }
    
    public void setPacksize(String packsize) {
        this.packsize = packsize;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }
    public Float getGst() {
        return this.gst;
    }
    
    public void setGst(Float gst) {
        this.gst = gst;
    }




}


