package greenInvoice.maps;
// Generated 19 Feb, 2019 9:57:44 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Instruments generated by hbm2java
 */
public class Instruments  implements java.io.Serializable {


     private Integer instrumentsId;
     private String catNo;
     private String descGoods;
     private String workingSize;
     private String moc;
     private String tempController;
     private double rate;
     private Set vouchers = new HashSet(0);
     private float gst;

    public float getGst() {
        return gst;
    }

    public void setGst(float gst) {
        this.gst = gst;
    }
    public Instruments() {
    }

	
    public Instruments(int rate) {
        this.rate = rate;
    }
    public Instruments(String catNo, String descGoods, String workingSize, String moc, String tempController, int rate, Set vouchers) {
       this.catNo = catNo;
       this.descGoods = descGoods;
       this.workingSize = workingSize;
       this.moc = moc;
       this.tempController = tempController;
       this.rate = rate;
       this.vouchers = vouchers;
    }
   
    public Integer getInstrumentsId() {
        return this.instrumentsId;
    }
    
    public void setInstrumentsId(Integer instrumentsId) {
        this.instrumentsId = instrumentsId;
    }
    public String getCatNo() {
        return this.catNo;
    }
    
    public void setCatNo(String catNo) {
        this.catNo = catNo;
    }
    public String getDescGoods() {
        return this.descGoods;
    }
    
    public void setDescGoods(String descGoods) {
        this.descGoods = descGoods;
    }
    public String getWorkingSize() {
        return this.workingSize;
    }
    
    public void setWorkingSize(String workingSize) {
        this.workingSize = workingSize;
    }
    public String getMoc() {
        return this.moc;
    }
    
    public void setMoc(String moc) {
        this.moc = moc;
    }
    public String getTempController() {
        return this.tempController;
    }
    
    public void setTempController(String tempController) {
        this.tempController = tempController;
    }
    public double getRate() {
        return this.rate;
    }
    
    public void setRate(double rate) {
        this.rate = rate;
    }
    public Set getVouchers() {
        return this.vouchers;
    }
    
    public void setVouchers(Set vouchers) {
        this.vouchers = vouchers;
    }




}


