package greenInvoice.maps;
// Generated 19 Feb, 2019 9:57:44 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Invoice generated by hbm2java
 */
public class Invoice  implements java.io.Serializable {


     private InvoiceId id;
     private Date doi;
     private String particulars;
     private Double dramt;
     private Double cramt;
     private Double paid;

    public Invoice() {
    }

	
    public Invoice(InvoiceId id) {
        this.id = id;
    }
    public Invoice(InvoiceId id, Date doi, String particulars, Double dramt, Double cramt, Double paid) {
       this.id = id;
       this.doi = doi;
       this.particulars = particulars;
       this.dramt = dramt;
       this.cramt = cramt;
       this.paid = paid;
    }
   
    public InvoiceId getId() {
        return this.id;
    }
    
    public void setId(InvoiceId id) {
        this.id = id;
    }
    public Date getDoi() {
        return this.doi;
    }
    
    public void setDoi(Date doi) {
        this.doi = doi;
    }
    public String getParticulars() {
        return this.particulars;
    }
    
    public void setParticulars(String particulars) {
        this.particulars = particulars;
    }
    public Double getDramt() {
        return this.dramt;
    }
    
    public void setDramt(Double dramt) {
        this.dramt = dramt;
    }
    public Double getCramt() {
        return this.cramt;
    }
    
    public void setCramt(Double cramt) {
        this.cramt = cramt;
    }
    public Double getPaid() {
        return this.paid;
    }
    
    public void setPaid(Double paid) {
        this.paid = paid;
    }




}


