package greenInvoice.maps;
// Generated 19 Feb, 2019 9:57:44 PM by Hibernate Tools 4.3.1



/**
 * Login generated by hbm2java
 */
public class Login  implements java.io.Serializable {


     private String email;
     private Usermaster usermaster;
     private String pwd;

    public Login() {
    }

    public Login(Usermaster usermaster, String pwd) {
       this.usermaster = usermaster;
       this.pwd = pwd;
    }
   
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Usermaster getUsermaster() {
        return this.usermaster;
    }
    
    public void setUsermaster(Usermaster usermaster) {
        this.usermaster = usermaster;
    }
    public String getPwd() {
        return this.pwd;
    }
    
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }




}


