package greenInvoice.maps;
// Generated 19 Feb, 2019 9:57:44 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Partymaster generated by hbm2java
 */
public class Partymaster  implements java.io.Serializable {


     private String partyno;
     private String partyname;
     private String address1;
     private String address2;
     private String city;
     private Integer pincode;
     private String email;
     private String phone;
     private Set vouchers = new HashSet(0);

    public Partymaster() {
    }

	
    public Partymaster(String partyno) {
        this.partyno = partyno;
    }
    public Partymaster(String partyno, String partyname, String address1, String address2, String city, Integer pincode, String email, String phone, Set vouchers) {
       this.partyno = partyno;
       this.partyname = partyname;
       this.address1 = address1;
       this.address2 = address2;
       this.city = city;
       this.pincode = pincode;
       this.email = email;
       this.phone = phone;
       this.vouchers = vouchers;
    }
   
    public String getPartyno() {
        return this.partyno;
    }
    
    public void setPartyno(String partyno) {
        this.partyno = partyno;
    }
    public String getPartyname() {
        return this.partyname;
    }
    
    public void setPartyname(String partyname) {
        this.partyname = partyname;
    }
    public String getAddress1() {
        return this.address1;
    }
    
    public void setAddress1(String address1) {
        this.address1 = address1;
    }
    public String getAddress2() {
        return this.address2;
    }
    
    public void setAddress2(String address2) {
        this.address2 = address2;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public Integer getPincode() {
        return this.pincode;
    }
    
    public void setPincode(Integer pincode) {
        this.pincode = pincode;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public Set getVouchers() {
        return this.vouchers;
    }
    
    public void setVouchers(Set vouchers) {
        this.vouchers = vouchers;
    }




}


