package greenInvoice.maps;
// Generated 19 Feb, 2019 9:57:44 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Salesregister generated by hbm2java
 */
public class Salesregister  implements java.io.Serializable {


     private Integer salesRegisterId;
     private Date dos;
     private String buyer;
     private String voucherNo;
     private Double amount;

    public Salesregister() {
    }

    public Salesregister(Date dos, String buyer, String voucherNo, Double amount) {
       this.dos = dos;
       this.buyer = buyer;
       this.voucherNo = voucherNo;
       this.amount = amount;
    }
   
    public Integer getSalesRegisterId() {
        return this.salesRegisterId;
    }
    
    public void setSalesRegisterId(Integer salesRegisterId) {
        this.salesRegisterId = salesRegisterId;
    }
    public Date getDos() {
        return this.dos;
    }
    
    public void setDos(Date dos) {
        this.dos = dos;
    }
    public String getBuyer() {
        return this.buyer;
    }
    
    public void setBuyer(String buyer) {
        this.buyer = buyer;
    }
    public String getVoucherNo() {
        return this.voucherNo;
    }
    
    public void setVoucherNo(String voucherNo) {
        this.voucherNo = voucherNo;
    }
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }




}


