package greenInvoice.maps;
// Generated 19 Feb, 2019 9:57:44 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * VoucherId generated by hbm2java
 */
public class VoucherId  implements java.io.Serializable {


     private String voucherno;
     private String partyno;
     private Date dos;
     private int productid;

    public VoucherId() {
    }

    public VoucherId(String voucherno, String partyno, Date dos, int productid) {
       this.voucherno = voucherno;
       this.partyno = partyno;
       this.dos = dos;
       this.productid = productid;
    }
   
    public String getVoucherno() {
        return this.voucherno;
    }
    
    public void setVoucherno(String voucherno) {
        this.voucherno = voucherno;
    }
    public String getPartyno() {
        return this.partyno;
    }
    
    public void setPartyno(String partyno) {
        this.partyno = partyno;
    }
    public Date getDos() {
        return this.dos;
    }
    
    public void setDos(Date dos) {
        this.dos = dos;
    }
    public int getProductid() {
        return this.productid;
    }
    
    public void setProductid(int productid) {
        this.productid = productid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VoucherId) ) return false;
		 VoucherId castOther = ( VoucherId ) other; 
         
		 return ( (this.getVoucherno()==castOther.getVoucherno()) || ( this.getVoucherno()!=null && castOther.getVoucherno()!=null && this.getVoucherno().equals(castOther.getVoucherno()) ) )
 && ( (this.getPartyno()==castOther.getPartyno()) || ( this.getPartyno()!=null && castOther.getPartyno()!=null && this.getPartyno().equals(castOther.getPartyno()) ) )
 && ( (this.getDos()==castOther.getDos()) || ( this.getDos()!=null && castOther.getDos()!=null && this.getDos().equals(castOther.getDos()) ) )
 && (this.getProductid()==castOther.getProductid());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getVoucherno() == null ? 0 : this.getVoucherno().hashCode() );
         result = 37 * result + ( getPartyno() == null ? 0 : this.getPartyno().hashCode() );
         result = 37 * result + ( getDos() == null ? 0 : this.getDos().hashCode() );
         result = 37 * result + this.getProductid();
         return result;
   }   


}


