package greenInvoice.maps;
// Generated 19 Feb, 2019 9:57:44 PM by Hibernate Tools 4.3.1



/**
 * Voucher generated by hbm2java
 */
public class Voucher  implements java.io.Serializable {


     private VoucherId id;
     private Glassware glassware;
     private Instruments instruments;
     private Partymaster partymaster;
     private Integer qty;
     private Double price;
     private String producttp;

    public Voucher() {
    }

	
    public Voucher(VoucherId id, Glassware glassware, Instruments instruments, Partymaster partymaster) {
        this.id = id;
        this.glassware = glassware;
        this.instruments = instruments;
        this.partymaster = partymaster;
    }
    public Voucher(VoucherId id, Glassware glassware, Instruments instruments, Partymaster partymaster, Integer qty, Double price, String producttp) {
       this.id = id;
       this.glassware = glassware;
       this.instruments = instruments;
       this.partymaster = partymaster;
       this.qty = qty;
       this.price = price;
       this.producttp = producttp;
    }
   
    public VoucherId getId() {
        return this.id;
    }
    
    public void setId(VoucherId id) {
        this.id = id;
    }
    public Glassware getGlassware() {
        return this.glassware;
    }
    
    public void setGlassware(Glassware glassware) {
        this.glassware = glassware;
    }
    public Instruments getInstruments() {
        return this.instruments;
    }
    
    public void setInstruments(Instruments instruments) {
        this.instruments = instruments;
    }
    public Partymaster getPartymaster() {
        return this.partymaster;
    }
    
    public void setPartymaster(Partymaster partymaster) {
        this.partymaster = partymaster;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }
    public String getProducttp() {
        return this.producttp;
    }
    
    public void setProducttp(String producttp) {
        this.producttp = producttp;
    }




}


